config/routes.rb
Rails.application.routes.draw do
  get 'profiles/:id/show'=>"profiles#show", :as=>'show_profile'

  get 'profiles/edit'

  get 'profiles/update'

  resources :posts
  post 'add_like_to_post/:id/:user_id' => "posts#add_like", :as => 'add_like_to_post'
  get 'user/index'

  get 'user/show'

  get 'home/index'
  get 'find_friends'=>"home#find_friends", :as=> 'find_friends'
  devise_for :users, controllers: {registrations: "registrations"}

  post 'comment/:post_id' => 'posts#comment', :as => 'comment_post'
  resources :profiles, only: [:show, :edit, :update]
  resources :friendships, only:[:create, :update, :destroy]
  devise_scope :user do
    root 'registrations#new'
  end

  as :user do

    get '/unused_email', to: 'registrations#unused_email'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
   @posts = current_user.post_feed(params[:page])
  end

  def find_friends
    @no_friends = current_user.no_friendship

    @friend_requests = current_user.requests_from
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/find_friends.html.erb
<h3>Friend requests</h3>
<% if @friend_requests.any? %>
    <% @friend_requests.each do |user| %>
        <div class="media">
          <div class="media-left">

            <% if user.profile.profile_img != nil %>
                <%= image_tag user.profile.profile_img.content.url(:thumb) %>
            <%end%>

          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to profile_path(user) do %>
                  <%= user.first_name.titleize + " " + user.last_name.titleize  %>
              <% end %>
            </h4>
            <div class="pull-left">
              <%= link_to 'Add to friends', friendship_path(user) ,:method=>'patch' , :class => 'btn btn-primary' %>
            </div>
            <div class="pull-left margin-left-10">
              <%= link_to 'Delete request', friendship_path(user) ,:method=>'delete' , :class => 'btn btn-primary' %>
            </div>
          </div>
        </div>
    <%end %>
<% else %>
    <p> No friend request...</p>
<% end %>
<h3>Search friends</h3>
<% if @no_friends.any? %>
    <% @no_friends.each do |user| %>
        <div class="media">
          <div class="media-left">

            <% if user.profile.profile_img != nil %>
                <%= image_tag user.profile.profile_img.content.url(:thumb) %>
            <%end%>

          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to profile_path(user) do %>
                  <%= user.first_name.titleize + " " + user.last_name.titleize  %>
              <% end %>
             </h4>
            <%= form_for Friendship.new, :url=>{controller:'friendships', action: 'create'},
                         :method=>:post ,
                         :html => { :class => "form-horizontal post", :id=>"requester_form_#{user.id}"} do |f| %>
                <%= f.hidden_field :requested_id, :value => user.id  %>
                <%= f.submit 'Send request', :class => 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
    <%end  %>
<% else %>
    <p> No people to know...</p>
<% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'posts/form' %>
    <div id="feeds">
      <%= render @posts %>
    </div>
    <div id="infinite-scrolling">
      <%= will_paginate @posts %>
    </div>

    <div class="end-posts">.....No more post to show.....</div>
  </div>
</div>

app/views/home/index.js.erb
$('#feeds').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');