config/routes.rb
Rails.application.routes.draw do
  get 'profiles/:id/show'=>"profiles#show", :as=>'show_profile'

  get 'profiles/edit'

  get 'profiles/update'

  resources :posts
  post 'add_like_to_post/:id/:user_id' => "posts#add_like", :as => 'add_like_to_post'
  get 'user/index'

  get 'user/show'

  get 'home/index'
  get 'find_friends'=>"home#find_friends", :as=> 'find_friends'
  devise_for :users, controllers: {registrations: "registrations"}

  post 'comment/:post_id' => 'posts#comment', :as => 'comment_post'
  resources :profiles, only: [:show, :edit, :update]
  resources :friendships, only:[:create, :update, :destroy]
  devise_scope :user do
    root 'registrations#new'
  end

  as :user do

    get '/unused_email', to: 'registrations#unused_email'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :image , :class_name=>'Picture', :as=>:imageable
  acts_as_likeable
  acts_as_commentable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :add_like]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    new_post_params = post_params
    if new_post_params[:image] != nil
    new_image = Picture.create({:content=> new_post_params[:image]})
      new_post_params[:image]= new_image
    end
    @post = Post.new(new_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_like
    @user = current_user
    @user.toggle_like!(@post)
    respond_to do |format|
      format.js
    end
  end

  def comment
    @post = Post.find(params[:post_id])
    comment = @post.comments.create
    comment.comment = params[:comment][:comment]
    comment.user = current_user
    comment.save
    #byebug

    respond_to do |format|
      format.js
    end

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :content, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper


end

app/views/posts/_comments.html.erb
<div class="comments">
  Comments (<%= post.comments.count %>):
  <% post.comments.each do |comment| %>
      <div class="media comment">
        <div class="media-left">
          <% if comment.user.profile.profile_img != nil %>
              <%= image_tag comment.user.profile.profile_img.content.url(:thumb) %>
          <% end %>
        </div>
        <div class="media-body">
          <h5 class="media-heading">
            <%= link_to profile_path(comment.user) do %>
                <%= comment.user.full_name %>
            <% end %>
          </h5>
          <p><%= comment.comment %></p>
        </div>
        <div class="time-ago"><%= time_ago_in_words(comment.created_at) %></div>
      </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for Post.new, :url=>{controller:'posts', action: 'create'},
             :method=>:post ,:remote=>true,
             :html => { :class => "form-horizontal post", :multipart => true},
              authenticity_token: true   do |f| %>

  <%= f.hidden_field :user_id, :value=>current_user.id %>
  <div class="form-group">
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
     <%= f.text_area :content, :class => 'form-control' %>
  </div>
  <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="card post">
  <div class="card-title ">
    <div class=" title-img">
      <%= image_tag post.user.profile.profile_img.content.url(:thumb)%>
    </div>
    <div class="title-content">
     <div> <%= link_to post.user.full_name , profile_path(post.user) %></div>
      <div class="time-ago"><%= time_ago_in_words(post.created_at) %></div>
    </div>

  </div>
  <div class="card-image">
    <% if post.image != nil %>
        <%= image_tag post.image.content.url(:medium), :class => 'img-responsive' %>
    <%end%>
  </div>

  <div class="card-content">
    <p><%= post.content %></p>
  </div>

  <div class="card-action">
    <p id="<%= "likes_count_#{post.id}" %>"><%= pluralize(post.likers(User).count, 'Like', 'Likes') %></p>
    <% if user_signed_in? %>
        <%= link_to current_user.likes?(post) ? 'Unlike':'Like', add_like_to_post_path(:id => post.id, :user_id => current_user.id), :id => "like_#{post.id}", :remote => true, :method => :post, :class => 'btn btn-default', :role => 'button' %>
    <% end %>
  </div>
  <div class="card-comments">
  <div id="<%= "comments_#{post.id}" %>">
    <%= render 'posts/comments', :post=>post %>
  </div>

   <%= form_for Comment.new , :url=>comment_post_path(post),
                :method=>:post ,:remote=>true do |f|  %>
    <%= f.hidden_field :post_id, :value=>post.id %>

    <div class="form-group">
      <%= f.text_area :comment, :class=>'form-control', :placeholder=>'Make your comment', :id=>"text_comment_#{post.id}" %>
    </div>
     <div class="form-group">
       <%= f.submit 'Send', :class => 'btn btn-primary' %>
     </div>

    <% end %>
  </div>
</div>

app/views/posts/_post_element.html.erb
<div class="card">
  <div class="card-image">
    <% if post.image != nil %>
        <%= image_tag post.image.content.url(:medium), :class => 'img-responsive' %>
    <%end%>
  </div>

  <div class="card-content">
    <p><%= post.content %></p>
  </div>

  <div class="card-action">
    <p id="<%= "likes_count_#{post.id}" %>"><%= pluralize(post.likers(User).count, 'Like', 'Likes') %></p>
    <% if user_signed_in? %>
        <%= link_to current_user.likes?(post) ? 'Unlike':'Like', add_like_to_post_path(:id => post.id, :user_id => current_user.id), :id => "like_#{post.id}", :remote => true, :method => :post, :class => 'btn btn-default', :role => 'button' %>
    <% end %>
  </div>
  <div class="card-comments">
  <div id="<%= "comments_#{post.id}" %>">
    <%= render 'posts/comments', :post=>post %>
  </div>

   <%= form_for Comment.new , :url=>comment_post_path(post),
                :method=>:post ,:remote=>true do |f|  %>
    <%= f.hidden_field :post_id, :value=>post.id %>

    <div class="form-group">
      <%= f.text_area :comment, :class=>'form-control', :placeholder=>'Make your comment', :id=>"text_comment_#{post.id}" %>
    </div>
     <div class="form-group">
       <%= f.submit 'Send', :class => 'btn btn-primary' %>
     </div>

    <% end %>
  </div>
</div>

app/views/posts/add_like.js.erb
<%= liked = @user.likes?(@post) %>
$('#<%= "like_#{@post.id}" %>').text("<%= liked ? 'Unlike' : 'Like' %>");
$('#<%= "likes_count_#{@post.id}" %>').text('<%= j pluralize(@post.likers(User).count, 'Like', 'Likes') %>');

app/views/posts/comment.js.erb
$("#<%= "comments_#{@post.id}" %>").html('<%= j render 'posts/comments', :post => @post %>');
$("#<%= "text_comment_#{@post.id}" %>").val('');

app/views/posts/create.js.erb
$('#feeds').prepend('<%= j render 'posts/post', :post=>@post %>');
$('#post_content').val("");
$('#post_image').val("");

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.user_id %></td>
        <td><%= post.content %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @post.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @post.content %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>