config/routes.rb
Rails.application.routes.draw do
  get 'profiles/:id/show'=>"profiles#show", :as=>'show_profile'

  get 'profiles/edit'

  get 'profiles/update'

  resources :posts
  post 'add_like_to_post/:id/:user_id' => "posts#add_like", :as => 'add_like_to_post'
  get 'user/index'

  get 'user/show'

  get 'home/index'
  get 'find_friends'=>"home#find_friends", :as=> 'find_friends'
  devise_for :users, controllers: {registrations: "registrations"}

  post 'comment/:post_id' => 'posts#comment', :as => 'comment_post'
  resources :profiles, only: [:show, :edit, :update]
  resources :friendships, only:[:create, :update, :destroy]
  devise_scope :user do
    root 'registrations#new'
  end

  as :user do

    get '/unused_email', to: 'registrations#unused_email'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Facebook" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Facebook</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
         <div class="navbar-right">
           <% if content_for? :header %>
           <%= yield :header %>
           <% end %>
           <% if current_user  %>
               <ul class="nav navbar-nav">
                 <li> <%= link_to current_user.first_name, show_profile_path(current_user) %></li>
                 <li> <%= link_to 'Home', home_index_path %></li>
                 <li> <%= link_to 'Find friends', find_friends_path %></li>
                 <li><%= link_to 'Edit profile', edit_profile_path(current_user) %></li>
                 <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete%></li>
               </ul>
            <% end %>
         </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
         <% if user_signed_in? %>
            <%=  yield :profile if content_for? :profile %>
            <% else %>
             <%=  yield :signup if content_for? :signup %>
          <% end%>
        <%= yield %>

        </div>
        <!--<div class="col-lg-3">-->
          <!--<div class="well sidebar-nav">-->
            <!--<h3>Sidebar</h3>-->
            <!--<ul class="nav nav-list">-->
              <!--<li class="nav-header">Sidebar</li>-->
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
        <!--</div>&lt;!&ndash;/span&ndash;&gt;-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>